// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ⚠️ CRITICAL: The CLI needs the direct connection (port 5432)
    // Use the variable you defined in .env for session mode
    url: process.env["DIRECT_URL"], 
  },
});