-- Create vendor_claims table for vendor claiming flow
-- Allows users to claim seeded vendors and link to their account with admin approval

CREATE TABLE public.vendor_claims (
  id bigint NOT NULL DEFAULT nextval('vendor_claims_id_seq'::regclass),
  vendor_id bigint NOT NULL REFERENCES public.vendors(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id),
  contact_email character varying(255) NOT NULL,
  contact_phone character varying(50),
  business_name character varying(255),
  status character varying(20) NOT NULL DEFAULT 'pending'::character varying,
  admin_notes text,
  reviewed_by uuid REFERENCES public.users(id),
  reviewed_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT vendor_claims_status_check CHECK (((status)::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])))
);

ALTER TABLE public.vendor_claims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME public.vendor_claims_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

ALTER TABLE public.vendor_claims ENABLE ROW LEVEL SECURITY;

-- Indexes for efficient lookups
CREATE INDEX idx_vendor_claims_vendor_id ON public.vendor_claims(vendor_id);
CREATE INDEX idx_vendor_claims_user_id ON public.vendor_claims(user_id);
CREATE INDEX idx_vendor_claims_status ON public.vendor_claims(status);

-- RLS policies
-- Allow anyone to view claims (for public transparency if needed)
CREATE POLICY "Anyone can view claims" ON public.vendor_claims
  FOR SELECT USING (true);

-- Allow authenticated users to create claims
CREATE POLICY "Authenticated users can create claims" ON public.vendor_claims
  FOR INSERT TO authenticated
  WITH CHECK (true);

-- Allow service role to manage all claims
CREATE POLICY "Service role can manage claims" ON public.vendor_claims
  FOR ALL USING (true);
