-- Fix album tables by ensuring they exist and have proper policies
-- This migration is safe to run multiple times

-- Drop existing tables if they exist to start fresh
DROP TABLE IF EXISTS public.vendor_album_photos CASCADE;
DROP TABLE IF EXISTS public.vendor_albums CASCADE;

-- Recreate vendor_albums table
create table public.vendor_albums (
  id bigint generated by default as identity primary key,
  vendor_id bigint not null references public.vendors(id) on delete cascade,
  title text not null,
  slug text not null,
  created_at timestamptz not null default now(),
  unique(vendor_id, slug)
);

-- Recreate vendor_album_photos table
create table public.vendor_album_photos (
  id bigint generated by default as identity primary key,
  vendor_id bigint not null references public.vendors(id) on delete cascade,
  album_id bigint not null references public.vendor_albums(id) on delete cascade,
  image_url text not null,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(album_id, image_url)
);

-- Create indexes for performance
create index idx_vendor_albums_vendor_id on public.vendor_albums(vendor_id);
create index idx_vendor_albums_slug on public.vendor_albums(slug);
create index idx_vendor_album_photos_vendor_id on public.vendor_album_photos(vendor_id);
create index idx_vendor_album_photos_album_id on public.vendor_album_photos(album_id);
create index idx_vendor_album_photos_image_url on public.vendor_album_photos(image_url);

-- Enable RLS
alter table public.vendor_albums enable row level security;
alter table public.vendor_album_photos enable row level security;

-- Public read policies
create policy "Public can view vendor albums"
on public.vendor_albums
for select
to public
using (true);

create policy "Public can view vendor album photos"
on public.vendor_album_photos
for select
to public
using (true);

-- Vendor write policies
create policy "Vendors can manage their albums"
on public.vendor_albums
for all
to authenticated
using (
  exists (
    select 1 from public.vendors v
    where v.id = vendor_albums.vendor_id
      and v.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.vendors v
    where v.id = vendor_albums.vendor_id
      and v.user_id = auth.uid()
  )
);

create policy "Vendors can manage their album photos"
on public.vendor_album_photos
for all
to authenticated
using (
  exists (
    select 1 from public.vendors v
    where v.id = vendor_album_photos.vendor_id
      and v.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.vendors v
    where v.id = vendor_album_photos.vendor_id
      and v.user_id = auth.uid()
  )
);