-- Create cities table
CREATE TABLE cities (
    id bigint generated by default as identity primary key,
    name text not null,
    region_id integer references regions(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;

-- Add index for fast lookups
CREATE INDEX idx_cities_region_id ON cities(region_id);

-- Policies for cities
CREATE POLICY "Cities are viewable by public."
  ON cities FOR SELECT
  USING (true);
