-- Add contact/admin fields to vendors table
ALTER TABLE vendors
ADD COLUMN contact_person_1_name text,
ADD COLUMN contact_person_1_position text,
ADD COLUMN contact_person_2_name text,
ADD COLUMN contact_person_2_position text,
ADD COLUMN admin_email_1 text,
ADD COLUMN admin_email_2 text,
ADD COLUMN admin_email_3 text,
ADD COLUMN admin_phone_1 text,
ADD COLUMN admin_phone_2 text,
ADD COLUMN admin_phone_3 text;

-- Create vendor_subscriptions table
CREATE TABLE vendor_subscriptions (
    id bigint generated by default as identity primary key,
    vendor_id integer references vendors(id) on delete cascade not null,
    plan_id integer references plans(id) on delete set null,
    status text not null default 'pending_verification',
    expiry_date date,
    verification_doc_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE vendor_subscriptions ENABLE ROW LEVEL SECURITY;

-- Policies for vendor_subscriptions
CREATE POLICY "Vendor subscriptions are viewable by public."
  ON vendor_subscriptions FOR SELECT
  USING (true);

CREATE POLICY "Vendors can insert their own subscriptions."
  ON vendor_subscriptions FOR INSERT
  WITH CHECK (auth.uid() IN (SELECT user_id FROM vendors WHERE id = vendor_id));

CREATE POLICY "Vendors can update their own subscriptions."
  ON vendor_subscriptions FOR UPDATE
  USING (auth.uid() IN (SELECT user_id FROM vendors WHERE id = vendor_id));

CREATE POLICY "Vendors can delete their own subscriptions."
  ON vendor_subscriptions FOR DELETE
  USING (auth.uid() IN (SELECT user_id FROM vendors WHERE id = vendor_id));
