-- 1. Create vendor_videos table
CREATE TABLE IF NOT EXISTS public.vendor_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id INTEGER REFERENCES public.vendors(id) ON DELETE CASCADE,
    video_url TEXT NOT NULL,
    title TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Move existing video links from vendor_images to vendor_videos
INSERT INTO public.vendor_videos (vendor_id, video_url, title, display_order, created_at)
SELECT vendor_id, image_url, caption, display_order, created_at
FROM public.vendor_images
WHERE image_url LIKE '%youtube.com%' 
   OR image_url LIKE '%youtu.be%' 
   OR image_url LIKE '%vimeo.com%';

-- 3. Delete those video links from the image table
DELETE FROM public.vendor_images
WHERE image_url LIKE '%youtube.com%' 
   OR image_url LIKE '%youtu.be%' 
   OR image_url LIKE '%vimeo.com%';

-- 4. Clean up failed assets from migration report
-- Set logo_url to NULL for vendors with dead links
UPDATE public.vendors
SET logo_url = NULL
WHERE id IN (367, 926, 671, 282, 652, 921, 684, 682);

-- Delete dead image records from vendor_images
DELETE FROM public.vendor_images
WHERE id IN (
    8774, 8775, 8776, 8779, 8780, 8777, 8778, 8781, 
    3760, 4300, 4301, 4446, 4672, 4695, 10889, 
    6034, 6035, 6036, 6037, 6211, 6206, 6207, 6208, 6209, 6210, 
    8686, 4471
);

-- 5. Set up RLS for vendor_videos
ALTER TABLE public.vendor_videos ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Videos are viewable by everyone" 
ON public.vendor_videos FOR SELECT 
TO public 
USING (true);

-- Vendor management access
CREATE POLICY "Vendor owners can manage their videos" 
ON public.vendor_videos FOR ALL 
TO authenticated 
USING (owns_vendor(vendor_id))
WITH CHECK (owns_vendor(vendor_id));

-- Admin management access
CREATE POLICY "Admins can manage all videos" 
ON public.vendor_videos FOR ALL 
TO authenticated 
USING (is_admin());
