create table "public"."marketplace_items" (
    "id" bigint generated by default as identity primary key,
    "vendor_id" integer not null references public.vendors(id) on delete cascade,
    "title" character varying(255) not null,
    "summary" text,
    "price" numeric(10,2) not null,
    "price_text" character varying(100),
    "image_url" character varying(500),
    "image_focus_x" numeric(5,2),
    "image_focus_y" numeric(5,2),
    "image_zoom" numeric(6,3),
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now() not null,
    "updated_at" timestamp with time zone default now() not null
);

create table "public"."saved_marketplace_items" (
    "user_id" uuid not null references public.users(id) on delete cascade,
    "marketplace_item_id" bigint not null references public.marketplace_items(id) on delete cascade,
    "target_amount" numeric(10,2) default 0,
    "contribution" numeric(10,2) default 0,
    "created_at" timestamp with time zone default now() not null,
    primary key ("user_id", "marketplace_item_id")
);

-- Enable RLS
alter table "public"."marketplace_items" enable row level security;
alter table "public"."saved_marketplace_items" enable row level security;

-- Marketplace Items Policies
create policy "Marketplace items are viewable by everyone"
on "public"."marketplace_items" for select
using (true);

create policy "Vendors can insert their own marketplace items"
on "public"."marketplace_items" for insert
with check (
    auth.uid() in (
        select user_id from public.vendors where id = vendor_id
    )
);

create policy "Vendors can update their own marketplace items"
on "public"."marketplace_items" for update
using (
    auth.uid() in (
        select user_id from public.vendors where id = vendor_id
    )
);

create policy "Vendors can delete their own marketplace items"
on "public"."marketplace_items" for delete
using (
    auth.uid() in (
        select user_id from public.vendors where id = vendor_id
    )
);

-- Saved Marketplace Items Policies
create policy "Users can view their own saved marketplace items"
on "public"."saved_marketplace_items" for select
using (auth.uid() = user_id);

create policy "Users can insert their own saved marketplace items"
on "public"."saved_marketplace_items" for insert
with check (auth.uid() = user_id);

create policy "Users can update their own saved marketplace items"
on "public"."saved_marketplace_items" for update
using (auth.uid() = user_id);

create policy "Users can delete their own saved marketplace items"
on "public"."saved_marketplace_items" for delete
using (auth.uid() = user_id);


